#!/usr/bin/env python3
import cgi
import cgitb
cgitb.enable()
import os
import datetime

default = "No Value Present"
d = datetime.date.today()

print("Content-Type: text/html")
print()

body = """<html>
<head>
<title>Lab 1 - CGI experiments</title>
</head>
<body>
<p>Hey there, this page has been generated by {software}, running {script}</p>
<p>Today is {month} {date}, {year}.</p>
<p>This page was requested by IP Address {client_ip}</p>
</body>
</html>""".format(
    software=os.environ.get('SERVER_SOFTWARE', default),
    script= os.environ.get('SCRIPT_NAME', default),
    month='{:02d}'.format(d.month),
    date='{:02d}'.format(d.day),
    year='{:04d}'.format(d.year),
    client_ip='eeee'
)
print(body)
