#!/usr/bin/env python3
import datetime


default = "No Value Set"
d = datetime.date.today()



body = """<html>
<head>
<title>Lab 3 - WSGI experiments</title>
</head>
<body>
<p>Hey there, this page has been generated by {software}, running at {path}</p>
<p>Today is {month} {date}, {year}.</p>
<p>This page was requested by IP Address {client_ip}</p>
</body>
</html>"""


def application(environ, start_response):
    import pprint
    pprint.pprint(environ)
    print(environ.keys())
    response_body = body.format(
        software=environ.get('SERVER_SOFTWARE', default),
        path=environ.get('PATH', default),
        month='{:02d}'.format(d.month),
        date='{:02d}'.format(d.day),
        year='{:04d}'.format(d.year),
        client_ip=environ.get('REMOTE_ADDR', default)
    )
    status = '200 OK'

    response_headers = [('Content-Type', 'text/html'),
                        ('Content-Length', str(len(response_body)))]
    start_response(status, response_headers)

    return [response_body.encode('utf8')]


if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    srv = make_server('localhost', 8080, application)
    srv.serve_forever()
